# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - lmdina-eureka-service

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Dockerize application
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/lmdina-eureka-service:latest .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/lmdina-eureka-service:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'lmdina-eureka-service'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b486f9e0349844278533540a0a227cbc }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_4de599d5b9da462fbffcbeb9d9d93340 }}/lmdina-eureka-service:latest'